# プロジェクトディレクトリに移動
# bundle installを実行
# シークレットキーの取得
# etc/environmentの配備
# アセットコンパイル
# dbの作成
# dbのマイグレート

#　nginx再起動
#  unicorn起動

- name: executed bundle installe
  shell: bash -lc "bundle install --path=vendor/bundle"
  args: 
    chdir: /home/{{__working_user}}/{{__pj_name}}


- name: get secret key
  shell: bash -lc "bundle exec rails secret"
  args: 
    chdir: /home/{{__working_user}}/{{__pj_name}}
  register: key

# - name: deployed environment file  
#   blockinfile:
#     dest: /etc/environment
#     insertafter: '^# xxxx'
#     content: |
#       DATABASE_PASSWORD={{ __database_password }}
#       SECRET_KEY_BASE={{ key.stdout }}
#   become: yes